config:
  platform-type: OpenDataHub
  platform-version: unknown
image:
  repository: ttl.sh/opendatahub-ai-gateway-operator
  tag: latest
leaderElect: true
replicas: 1
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 128Mi
serviceAccount: {}
